### ISSUE TITLE
Feature : Notebooks chapter 2

### ISSUE THREAD

**Issue by YannSc** [eddes/buildingphysics#3]
## TODO
- [x] Add  PCM exemple with  Tf and dTf as sliders
- [x] Add filtration example with qv and m_c as sliders 
- [x] Add PID tank example with BP, Ti, Td and Qmax as sliders
